#include "AIWorkloadGenerator.h"
#include <iostream>
#include <sstream>
#include <algorithm>
#include <regex>
#include <cstdlib>
#include <cstdio>

#ifdef _WIN32
#define popen _popen
#define pclose _pclose
#endif

// ANSI colors for logs
namespace AIC {
    constexpr const char* RESET   = "\033[0m";
    constexpr const char* BOLD    = "\033[1m";
    constexpr const char* GREEN   = "\033[32m";
    constexpr const char* YELLOW  = "\033[33m";
    constexpr const char* CYAN    = "\033[36m";
    constexpr const char* RED     = "\033[31m";
}

std::vector<Process> AIWorkloadGenerator::generateWorkload(const std::string& prompt) {
    std::string cleanPrompt = prompt;
    // Strip surrounding spaces
    cleanPrompt.erase(0, cleanPrompt.find_first_not_of(" \t\r\n"));
    cleanPrompt.erase(cleanPrompt.find_last_not_of(" \t\r\n") + 1);

    if (cleanPrompt.empty()) {
        std::cout << AIC::RED << "⚠️ Prompt cannot be empty. Generating default workload." << AIC::RESET << std::endl;
        return generateOfflineWorkload("default");
    }

    // Check if DEEPSEEK_API_KEY is available
    const char* apiKeyEnv = std::getenv("DEEPSEEK_API_KEY");
    if (apiKeyEnv && std::string(apiKeyEnv).length() > 5) {
        std::string apiKey = std::string(apiKeyEnv);
        std::cout << AIC::CYAN << "[AIWorkloadGenerator] DEEPSEEK_API_KEY detected! Querying DeepSeek AI..." << AIC::RESET << std::endl;
        
        std::string apiResponse = callDeepSeekAPI(cleanPrompt, apiKey);
        if (!apiResponse.empty()) {
            std::vector<Process> apiProcList = parseJSONResponse(apiResponse);
            if (!apiProcList.empty()) {
                std::cout << AIC::GREEN << "🚀 [AIWorkloadGenerator] Successfully loaded " << apiProcList.size() 
                          << " processes dynamically generated by DeepSeek AI!" << AIC::RESET << std::endl;
                return apiProcList;
            }
        }
        std::cout << AIC::YELLOW << "⚠️ [AIWorkloadGenerator] DeepSeek API query failed or returned invalid JSON. Falling back to local offline smart engine..." << AIC::RESET << std::endl;
    } else {
        std::cout << AIC::CYAN << "[AIWorkloadGenerator] DEEPSEEK_API_KEY env not configured. Using local offline smart generation engine..." << AIC::RESET << std::endl;
    }

    return generateOfflineWorkload(cleanPrompt);
}

std::vector<Process> AIWorkloadGenerator::generateOfflineWorkload(const std::string& prompt) {
    std::string lowerPrompt = prompt;
    std::transform(lowerPrompt.begin(), lowerPrompt.end(), lowerPrompt.begin(), ::tolower);

    std::vector<Process> procList;

    if (lowerPrompt.find("game") != std::string::npos || lowerPrompt.find("gaming") != std::string::npos) {
        std::cout << AIC::GREEN << "[AI Engine] Recognized prompt: 'Gaming Workload'" << AIC::RESET << std::endl;
        procList.emplace_back(1, 0, 8, 1); // GameEngine (PID: 1, Arrival: 0, Burst: 8, Prio: 1)
        procList.back().name = "GameEngine";
        procList.emplace_back(2, 1, 3, 2); // DiscordVoice (PID: 2, Arrival: 1, Burst: 3, Prio: 2)
        procList.back().name = "DiscordVoice";
        procList.emplace_back(3, 2, 6, 3); // OBSRecording (PID: 3, Arrival: 2, Burst: 6, Prio: 3)
        procList.back().name = "OBSRecording";
        procList.emplace_back(4, 0, 2, 4); // SteamClient (PID: 4, Arrival: 0, Burst: 2, Prio: 4)
        procList.back().name = "SteamClient";
    }
    else if (lowerPrompt.find("smartphone") != std::string::npos || lowerPrompt.find("phone") != std::string::npos || lowerPrompt.find("multitask") != std::string::npos) {
        std::cout << AIC::GREEN << "[AI Engine] Recognized prompt: 'Smartphone Multitasking'" << AIC::RESET << std::endl;
        procList.emplace_back(1, 0, 3, 1); // UI_System
        procList.back().name = "UI_System";
        procList.emplace_back(2, 1, 5, 3); // MusicPlayer
        procList.back().name = "MusicPlayer";
        procList.emplace_back(3, 2, 7, 4); // SocialMedia
        procList.back().name = "SocialMedia";
        procList.emplace_back(4, 3, 6, 2); // WebBrowser
        procList.back().name = "WebBrowser";
        procList.emplace_back(5, 5, 2, 5); // EmailSync
        procList.back().name = "EmailSync";
    }
    else if (lowerPrompt.find("hospital") != std::string::npos || lowerPrompt.find("emergency") != std::string::npos || lowerPrompt.find("medical") != std::string::npos) {
        std::cout << AIC::GREEN << "[AI Engine] Recognized prompt: 'Hospital Emergency System'" << AIC::RESET << std::endl;
        procList.emplace_back(1, 0, 10, 1); // ICU_Monitor
        procList.back().name = "ICU_Monitor";
        procList.emplace_back(2, 1, 4, 2); // PatientTracker
        procList.back().name = "PatientTracker";
        procList.emplace_back(3, 3, 3, 3); // NurseDispatch
        procList.back().name = "NurseDispatch";
        procList.emplace_back(4, 8, 6, 4); // BillingService
        procList.back().name = "BillingService";
    }
    else if (lowerPrompt.find("web") != std::string::npos || lowerPrompt.find("server") != std::string::npos || lowerPrompt.find("network") != std::string::npos) {
        std::cout << AIC::GREEN << "[AI Engine] Recognized prompt: 'Web Server Workload'" << AIC::RESET << std::endl;
        procList.emplace_back(1, 0, 2, 1); // RequestRouter
        procList.back().name = "RequestRouter";
        procList.emplace_back(2, 1, 7, 2); // DB_Query
        procList.back().name = "DB_Query";
        procList.emplace_back(3, 3, 4, 3); // StaticFileSrv
        procList.back().name = "StaticFileSrv";
        procList.emplace_back(4, 2, 3, 2); // AuthValidator
        procList.back().name = "AuthValidator";
        procList.emplace_back(5, 6, 5, 4); // CacheLogger
        procList.back().name = "CacheLogger";
    }
    else if (lowerPrompt.find("database") != std::string::npos || lowerPrompt.find("sql") != std::string::npos) {
        std::cout << AIC::GREEN << "[AI Engine] Recognized prompt: 'Database Server'" << AIC::RESET << std::endl;
        procList.emplace_back(1, 0, 2, 2); // QueryParser
        procList.back().name = "QueryParser";
        procList.emplace_back(2, 1, 5, 1); // IndexSearcher
        procList.back().name = "IndexSearcher";
        procList.emplace_back(3, 3, 8, 3); // DiskWriter
        procList.back().name = "DiskWriter";
    }
    else if (lowerPrompt.find("ml") != std::string::npos || lowerPrompt.find("training") != std::string::npos || lowerPrompt.find("ai") != std::string::npos) {
        std::cout << AIC::GREEN << "[AI Engine] Recognized prompt: 'Machine Learning Training'" << AIC::RESET << std::endl;
        procList.emplace_back(1, 0, 4, 3); // DataLoader
        procList.back().name = "DataLoader";
        procList.emplace_back(2, 2, 15, 1); // GPU_Compute
        procList.back().name = "GPU_Compute";
        procList.emplace_back(3, 10, 3, 2); // WeightSaver
        procList.back().name = "WeightSaver";
    }
    else {
        std::cout << AIC::GREEN << "[AI Engine] Generative baseline for prompt: '" << prompt << "'" << AIC::RESET << std::endl;
        // Generic customized generative scenario
        procList.emplace_back(1, 0, 4, 2);
        procList.back().name = "SystemCore";
        procList.emplace_back(2, 1, 6, 1);
        procList.back().name = "DataParser";
        procList.emplace_back(3, 3, 3, 3);
        procList.back().name = "NetThread";
        procList.emplace_back(4, 6, 5, 4);
        procList.back().name = "AuditLogger";
    }

    return procList;
}

std::string AIWorkloadGenerator::callDeepSeekAPI(const std::string& prompt, const std::string& apiKey) {
    // 1. Clean the prompt of unsafe shell characters
    std::string safePrompt = prompt;
    safePrompt.erase(std::remove(safePrompt.begin(), safePrompt.end(), '"'), safePrompt.end());
    safePrompt.erase(std::remove(safePrompt.begin(), safePrompt.end(), '\\'), safePrompt.end());
    safePrompt.erase(std::remove(safePrompt.begin(), safePrompt.end(), '`'), safePrompt.end());
    safePrompt.erase(std::remove(safePrompt.begin(), safePrompt.end(), '\n'), safePrompt.end());

    // 2. Build the curl system command
    // We request the model to return a raw JSON list of processes with properties: pid, name, arrival, burst, priority.
    std::string url = "https://api.deepseek.com/chat/completions";
    
    std::ostringstream jsonStream;
    jsonStream << "{\\\"model\\\":\\\"deepseek-chat\\\",\\\"messages\\\":[{\\\"role\\\":\\\"user\\\",\\\"content\\\":\\\"Generate a valid raw JSON array of realistic processes for: '" 
               << safePrompt << "'. Format: [ {\\\\\\\"pid\\\\\\\":1, \\\\\\\"name\\\\\\\":\\\\\\\"GameEngine\\\\\\\", \\\\\\\"arrival\\\\\\\":0, \\\\\\\"burst\\\\\\\":8, \\\\\\\"priority\\\\\\\":1} ]. Only return the JSON array, no markdown wrappers, no backticks, no comments, no extra text.\\\"}],\\\"temperature\\\":0.2}";
    
    std::string cmd = "curl -s -X POST \"" + url + "\" ";
    cmd += "-H \"Content-Type: application/json\" ";
    cmd += "-H \"Authorization: Bearer " + apiKey + "\" ";
    cmd += "-d \"" + jsonStream.str() + "\"";

    // 3. Open pipeline
    FILE* fp = popen(cmd.c_str(), "r");
    if (!fp) {
        std::cerr << "❌ [AIWorkloadGenerator] Failed to open curl subprocess pipeline!" << std::endl;
        return "";
    }

    char buffer[1024];
    std::string result = "";
    while (fgets(buffer, sizeof(buffer), fp) != NULL) {
        result += buffer;
    }
    pclose(fp);
    return result;
}

std::string extractJSONStringField(const std::string& json, const std::string& fieldName) {
    size_t pos = json.find("\"" + fieldName + "\"");
    if (pos == std::string::npos) {
        return "";
    }
    pos = json.find(":", pos + fieldName.length() + 2);
    if (pos == std::string::npos) {
        return "";
    }
    pos = json.find("\"", pos + 1);
    if (pos == std::string::npos) {
        return "";
    }
    size_t start = pos + 1;
    std::string value = "";
    for (size_t i = start; i < json.length(); ++i) {
        if (json[i] == '\\') {
            if (i + 1 < json.length()) {
                char c = json[i + 1];
                if (c == 'n') value += '\n';
                else if (c == 't') value += '\t';
                else if (c == 'r') value += '\r';
                else value += c;
                i++;
            }
        } else if (json[i] == '"') {
            break; // End of string
        } else {
            value += json[i];
        }
    }
    return value;
}

std::vector<Process> AIWorkloadGenerator::parseJSONResponse(const std::string& jsonStr) {
    std::vector<Process> processes;

    // Extract the inner content/text field to handle double escaping properly
    std::string textContent = extractJSONStringField(jsonStr, "content");
    if (textContent.empty()) {
        textContent = extractJSONStringField(jsonStr, "text");
    }
    
    // Fallback to the whole raw string if we didn't find those fields
    if (textContent.empty()) {
        textContent = jsonStr;
    }
    
    // Now isolate the process array using brackets
    size_t startBracket = textContent.find('[');
    size_t endBracket = textContent.rfind(']');
    
    if (startBracket != std::string::npos && endBracket != std::string::npos && endBracket > startBracket) {
        textContent = textContent.substr(startBracket, endBracket - startBracket + 1);
    } else {
        return processes;
    }

    // Parse each process object in the JSON array: { "pid": 1, "name": "GameEngine", "arrival": 0, "burst": 8, "priority": 1 }
    // We use a regex to match process structures
    std::regex objRegex("\\{[^{}]*\\}");
    auto words_begin = std::sregex_iterator(textContent.begin(), textContent.end(), objRegex);
    auto words_end = std::sregex_iterator();

    for (std::sregex_iterator it = words_begin; it != words_end; ++it) {
        std::string objStr = it->str();

        // Extract properties using regexes
        std::regex pidReg("\"pid\"\\s*:\\s*([0-9]+)");
        std::regex nameReg("\"name\"\\s*:\\s*\"([^\"]+)\"");
        std::regex arrivalReg("\"(arrival|arrivalTime)\"\\s*:\\s*([0-9]+)");
        std::regex burstReg("\"(burst|burstTime)\"\\s*:\\s*([0-9]+)");
        std::regex prioReg("\"(priority)\"\\s*:\\s*([0-9]+)");

        std::smatch match;
        int pid = 0;
        std::string name = "";
        int arrival = 0;
        int burst = 0;
        int priority = 0;

        if (std::regex_search(objStr, match, pidReg) && match.size() > 1) pid = std::stoi(match[1].str());
        if (std::regex_search(objStr, match, nameReg) && match.size() > 1) name = match[1].str();
        if (std::regex_search(objStr, match, arrivalReg) && match.size() > 2) arrival = std::stoi(match[2].str());
        if (std::regex_search(objStr, match, burstReg) && match.size() > 2) burst = std::stoi(match[2].str());
        if (std::regex_search(objStr, match, prioReg) && match.size() > 2) priority = std::stoi(match[2].str());

        if (pid > 0 && burst > 0) {
            processes.emplace_back(pid, arrival, burst, priority);
            if (!name.empty()) {
                processes.back().name = name;
            }
        }
    }

    return processes;
}
